- name: Run FCS IaC Scan
  uses: crowdstrike/fcs-action@v4.0.1
  with:
    falcon_client_id: ${{ vars.FALCON_CLIENT_ID }}
    falcon_region: 'us-1'
    path: './my-iac-directory'
    project_name: '${{ github.repository }}/${{ github.ref_name }}'
  env:
    FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
